const products = [
  // 🌿 PODI
  {
    name: "Murungai Idly/Rice Podi",
    category: "Podi",
    price50: "₹40 (50 gms)",
    price100: "₹60 (100 gms)",
    price: 40, // default to 50g
    stock: true,
    image: "images/Moringa powder drumstick.png",
  },
  {
    name: "Karuvepillai Idly/Rice Podi",
    category: "Podi",
    price50: "₹40 (50 gms)",
    price100: "₹60 (100 gms)",
    price: 40,
    stock: true,
    image: "images/pure curry leaf powder.png",
  },
  {
    name: "Sambar Podi",
    category: "Podi",
    price50: "₹40 (50 gms)",
    price100: "₹60 (100 gms)",
    price: 40,
    stock: true,
    image: "images/Sambar Powder.png",
  },

  // 🍚 RICE MIX
  {
    name: "Seerukeerai Rice Mix",
    category: "Rice Mix",
    price50: "₹65 (50 gms)",
    price100: "₹110 (100 gms)",
    price: 65,
    stock: true,
    image: "images/SiruKeerai rice mix.png",
  },
  {
    name: "Poondu Rice Mix",
    category: "Rice Mix",
    price50: "₹50 (50 gms)",
    price100: "₹100 (100 gms)",
    price: 50,
    stock: true,
    image: "images/GarlicRice mix.png",
  },
  {
    name: "Paruppu Rice Mix",
    category: "Rice Mix",
    price50: "₹50 (50 gms)",
    price100: "₹80 (100 gms)",
    price: 50,
    stock: true,
    image: "images/paruppu podi.png",
  },
  {
    name: "Perandai Rice Mix",
    category: "Rice Mix",
    price50: "₹60 (50 gms)",
    price100: "₹110 (100 gms)",
    price: 60,
    stock: true,
    image: "images/Pirandai veldt grape rice mix.png",
  },
  {
    name: "Nellikai Rice Mix",
    category: "Rice Mix",
    price50: "₹65 (50 gms)",
    price100: "₹110 (100 gms)",
    price: 65,
    stock: true,
    image: "images/nellikkai gooseberry rice mix.png",
  },

  // 🍵 SOUP MIX
  {
    name: "Murungai Soup Mix (16 Soups)",
    category: "Soup Mix",
    price50: "₹85 (16 Soups)",
    price100: null,
    price: 85,
    stock: true,
    image: "images/Moringa soup.png",
  },
  {
    name: "Nellikai Soup Mix (13 Soups)",
    category: "Soup Mix",
    price50: "₹85 (13 Soups)",
    price100: null,
    price: 85,
    stock: true,
    image: "images/nellikkai soup mix powder.png",
  },
  {
    name: "Banana Stem Soup Mix (13 Soups)",
    category: "Soup Mix",
    price50: "₹85 (13 Soups)",
    price100: null,
    price: 85,
    stock: true,
    image: "images/banana stem soup mix powder.png",
  },
  {
    name: "Avaram Poo Soup Mix (16 Soups)",
    category: "Soup Mix",
    price50: "₹110 (16 Soups)",
    price100: null,
    price: 110,
    stock: true,
    image: "images/Avarampoo soup mix.png",
  },

  // 🌼 POWDER
  {
    name: "Pure Nellikai Powder",
    category: "Powder",
    price50: "₹65 (50 gms)",
    price100: "₹110 (100 gms)",
    price: 65,
    stock: true,
    image: "images/Pure gooseberry powder.png",
  },
  {
    name: "Pure Avaram Poo Powder",
    category: "Powder",
    price50: "₹90 (50 gms)",
    price100: "₹170 (100 gms)",
    price: 90,
    stock: true,
    image: "images/Pure avarampoo powder.png",
  },
  {
    name: "Pure Karuvepillai Powder",
    category: "Powder",
    price50: "₹50 (50 gms)",
    price100: "₹100 (100 gms)",
    price: 50,
    stock: true,
    image: "images/kariveppilai powder.png",
  },
];

export default products;
